(function(){
const S={rev:null,rt:null,lock:{id:null,t:'',client:'',owned:false,blocked:false,busy:false,h:null}};
const el=id=>document.getElementById(id);
function wait(){if(!window.__invoiceCoreInstalled||typeof window.api!=='function'||typeof window.saveNow!=='function')return setTimeout(wait,80);setup()}
function setup(){if(window.__invoiceSuiteInstalled)return;window.__invoiceSuiteInstalled=true;style();workflow();fees();revisions();locks()}
function style(){const x=document.createElement('style');x.textContent='.workflow-legacy{display:none!important}.workflow-primary{min-width:205px}.suite-list{display:flex;flex-direction:column;gap:6px;max-height:220px;overflow:auto}.suite-row{display:grid;grid-template-columns:1fr auto auto;gap:6px;align-items:center;border:1px solid var(--line);padding:8px;border-radius:9px}.suite-row small{display:block;color:var(--muted)}.lock-banner{display:none;background:#fff4e5;border:1px solid #f0c46a;color:#754300;border-radius:10px;padding:8px 10px;font-size:12px;font-weight:900}.lock-banner.show{display:block}.rev-lines{max-height:50vh;overflow:auto;border:1px solid var(--line);border-radius:10px}.rev-lines table{min-width:760px}@media(max-width:620px){.suite-row{grid-template-columns:1fr}.workflow-primary{width:100%}}';document.head.appendChild(x)}
function ready(){const c=(customers||[]).find(x=>x.id===invoice.customer_id),vs=c?.vehicles||[];return !!invoice.customer_id&&(!vs.length||!!invoice.vehicle_id)&&(invoice.lines||[]).some(l=>Number(l.qty)>0&&Number(l.price)>0&&String(l.description||'').trim())}
function workflow(){const w=document.querySelector('.workflow');if(!w)return;['toEstimate','toRO','toInvoice'].forEach(id=>el(id)?.classList.add('workflow-legacy'));let b=el('workflowPrimary');if(!b){b=document.createElement('button');b.id='workflowPrimary';b.className='green workflow-primary';w.appendChild(b);b.onclick=()=>b.dataset.next&&changeWorkflow(b.dataset.next)}function refresh(){const m={Draft:['Estimate','Create Estimate'],Estimate:['Repair Order','Convert to Repair Order'],'Repair Order':['Invoice','Create Invoice']},n=m[invoice.status];b.style.display=n&&!invoice.read_only?'inline-flex':'none';if(n){b.dataset.next=n[0];b.textContent=n[1];b.disabled=S.lock.blocked||!ready()}}refresh();new MutationObserver(refresh).observe(document.querySelector('.app'),{childList:true,subtree:true})}
function modal(){if(el('fdModal'))return;const x=document.createElement('div');x.id='fdModal';x.className='modal-overlay';x.innerHTML='<div class="modal"><div class="modal-top"><h2 id="fdTitle">Fee</h2><button class="close" onclick="closeModal(\'fdModal\')">×</button></div><div class="modal-body stack"><input id="fdType" type="hidden"><div><label>Description</label><input id="fdDesc"></div><div id="feeBox" class="grid2"><div><label>Quantity</label><input id="fdQty" type="number" step=".01" value="1"></div><div><label>Fee Total</label><input id="fdTotal" type="number" step=".01" value="0"></div></div><div id="discBox" class="grid2 hidden"><div><label>Discount Type</label><select id="fdMode"><option value="percent">Percent %</option><option value="amount">Dollar Amount</option></select></div><div><label>Value</label><input id="fdValue" type="number" step=".01" value="0"></div></div><div id="fdPreview" class="notice"></div><div class="mini-row"><button class="light" id="fdSave">Save for Reuse</button><button class="green" id="fdAdd">Add to Invoice</button></div><div><label id="fdSavedLabel"></label><div id="fdSaved" class="suite-list"></div></div></div></div>';document.body.appendChild(x);el('fdSave').onclick=savePreset;el('fdAdd').onclick=addCurrent;el('fdMode').onchange=preview;el('fdValue').oninput=preview}
function base(){const t=calc();return Math.max(0,Number(t.labor||0)+Number(t.parts||0)+Number(t.fees||0))}
function damt(mode,v){v=Math.max(0,Number(v)||0);return round(mode==='percent'?base()*v/100:v)}
function preview(){if(el('fdType')?.value!=='Discount')return el('fdPreview').textContent='';el('fdPreview').textContent='Discount: '+money(damt(el('fdMode').value,el('fdValue').value))+' from '+money(base())+' labor + parts + fees.'}
function saved(type){const list=(presets||[]).filter(p=>p.preset_type===type);el('fdSavedLabel').textContent='Saved '+(type==='Fee'?'Fees':'Discounts');el('fdSaved').innerHTML=list.map(p=>{const d=p.payload||{},txt=type==='Fee'?money(d.total||0):(d.mode==='percent'?(d.value||0)+'%':money(d.value||0));return `<div class="suite-row"><div><strong>${esc(p.name)}</strong><small>${txt}</small></div><button class="blue" onclick="invoiceUsePreset('${p.id}')">Use</button><button class="light" onclick="invoiceDeletePreset('${p.id}')">Delete</button></div>`}).join('')||'<div class="empty">None saved yet.</div>'}
function openFD(type){modal();el('fdType').value=type;el('fdTitle').textContent='Add '+type;el('fdDesc').value=type;el('feeBox').classList.toggle('hidden',type!=='Fee');el('discBox').classList.toggle('hidden',type!=='Discount');el('fdQty').value=1;el('fdTotal').value=0;el('fdMode').value='percent';el('fdValue').value=0;preview();saved(type);openModal('fdModal')}
function addFee(d,q,total){q=Math.max(.01,Number(q)||1);total=Math.max(0,round(total));invoice.lines.push({id:uid(),type:'Fee',description:d||'Fee',qty:q,cost:0,price:round(total/q),taxable:false,tech:''});renderLines();queueSave()}
function addDisc(d,mode,v){const a=damt(mode,v);if(a<=0)return alert('Discount amount is $0.00.');invoice.lines.push({id:uid(),type:'Discount',description:d||'Discount',qty:1,cost:0,price:a,taxable:false,tech:''});renderLines();queueSave()}
function addCurrent(){const t=el('fdType').value,d=el('fdDesc').value.trim()||t;t==='Fee'?addFee(d,el('fdQty').value,el('fdTotal').value):addDisc(d,el('fdMode').value,el('fdValue').value);closeModal('fdModal');showTab('lines')}
async function savePreset(){const t=el('fdType').value,n=el('fdDesc').value.trim()||t,p=t==='Fee'?{description:n,qty:Number(el('fdQty').value)||1,total:Math.max(0,round(el('fdTotal').value))}:{description:n,mode:el('fdMode').value,value:Math.max(0,round(el('fdValue').value))};if((t==='Fee'?p.total:p.value)<=0)return alert('Enter a value first.');const j=await api('invoice-preset',{method:'POST',body:{preset_type:t,name:n,payload:p}});presets.unshift(j.preset);saved(t)}
window.invoiceUsePreset=id=>{const p=(presets||[]).find(x=>x.id===id),d=p?.payload||{};if(!p)return;p.preset_type==='Fee'?addFee(d.description||p.name,d.qty||1,d.total||0):addDisc(d.description||p.name,d.mode||'amount',d.value||0);closeModal('fdModal');showTab('lines')};
window.invoiceDeletePreset=async id=>{if(!confirm('Delete this saved preset?'))return;await api('invoice-preset',{method:'DELETE',params:{id}});presets=presets.filter(x=>x.id!==id);saved(el('fdType').value)};
function fees(){modal();const old=window.openLineModal;window.openLineModal=t=>(t==='Fee'||t==='Discount')?openFD(t):old(t)}
function revModal(){if(el('revModal'))return;const x=document.createElement('div');x.id='revModal';x.className='modal-overlay';x.innerHTML='<div class="modal" style="width:min(1100px,97vw)"><div class="modal-top"><h2 id="revTitle">Revision</h2><button class="close" onclick="invoiceCloseRevision()">×</button></div><div class="modal-body stack"><div class="mini-row"><button class="blue" onclick="invoiceRevAdd(\'Labor\')">+ Labor</button><button class="blue" onclick="invoiceRevAdd(\'Part\')">+ Part</button><button class="light" onclick="invoiceRevAdd(\'Fee\')">+ Fee</button><button class="light" onclick="invoiceRevAdd(\'Discount\')">+ Discount</button><span id="revStatus" class="notice">Ready</span></div><div class="rev-lines"><table class="line-table"><thead><tr><th>Type</th><th>Description</th><th>Qty</th><th>Cost</th><th>Price</th><th>Total</th><th></th></tr></thead><tbody id="revBody"></tbody></table></div><div><label>Internal Revision Notes</label><textarea id="revNotes"></textarea></div></div><div class="modal-foot"><button class="light" onclick="invoiceCloseRevision()">Done</button><button class="green" onclick="invoiceSendRevision()">Send to Order</button></div></div>';document.body.appendChild(x);el('revNotes').oninput=qrev}
function rrender(){el('revBody').innerHTML=(S.rev?.lines||[]).map(l=>`<tr><td><span class="type-badge ${String(l.type).toLowerCase()}">${esc(l.type)}</span></td><td><input value="${esc(l.description||'')}" oninput="invoiceRevEdit('${l.id}','description',this.value,false)"></td><td><input type="number" step=".01" value="${Number(l.qty)||0}" onchange="invoiceRevEdit('${l.id}','qty',this.value,true)"></td><td>${l.type==='Part'?`<input type="number" step=".01" value="${Number(l.cost||0)}" onchange="invoiceRevEdit('${l.id}','cost',this.value,true)">`:'—'}</td><td><input type="number" step=".01" value="${Number(l.price)||0}" onchange="invoiceRevEdit('${l.id}','price',this.value,true)"></td><td class="line-total">${money((Number(l.qty)||0)*(Number(l.price)||0))}</td><td><button class="danger icon-btn" onclick="invoiceRevRemove('${l.id}')">×</button></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">No revision lines.</div></td></tr>'}
async function loadRev(){const box=el('revisionList');if(!invoice.customer_id)return box.innerHTML='<div class="empty">Choose a customer to see revisions.</div>';const j=await api('invoices',{params:{customer_id:invoice.customer_id,status:'Revision',limit:200}});let a=j.invoices||[];if(invoice.vehicle_id)a=a.filter(x=>x.vehicle_id===invoice.vehicle_id);box.innerHTML=a.map(r=>`<div class="history-card"><strong>${esc(r.document_number||'Revision')}</strong><small>${(r.lines||[]).length} lines · ${money(r.total||0)}</small><div class="mini-row" style="margin-top:7px"><button class="blue" onclick="invoiceOpenRevision('${r.id}')">Review / Edit</button><button class="green" onclick="invoiceOpenRevision('${r.id}',true)">Send to Order</button><button class="light" onclick="deleteInvoice('${r.id}').then(loadRevisions)">Delete</button></div></div>`).join('')||'<div class="empty">No revisions for this customer / vehicle.</div>'}
window.invoiceOpenRevision=async(id,send=false)=>{revModal();const j=await api('invoices',{params:{id}});if(!j.invoice)return;S.rev=normalizeInvoice(j.invoice);S.rev.lines=(S.rev.lines||[]).map(l=>({...l,id:l.id||uid()}));el('revTitle').textContent='Revision · '+(S.rev.document_number||'Draft');el('revNotes').value=S.rev.internal_notes||'';rrender();if(send)return invoiceSendRevision();openModal('revModal')};
window.invoiceRevEdit=(id,f,v,re)=>{const l=S.rev.lines.find(x=>x.id===id);if(!l)return;l[f]=['qty','cost','price'].includes(f)?round(v):v;if(f==='cost'&&l.type==='Part')l.price=round(l.cost*(1+Number(settings.parts_markup_percent||0)/100));if(re)rrender();qrev()};
window.invoiceRevAdd=t=>{S.rev.lines.push({id:uid(),type:t,description:t==='Labor'?'Labor operation':t==='Part'?'Part / material':t,qty:1,cost:0,price:t==='Labor'?Number(settings.labor_rate||150):0,taxable:t==='Part',tech:''});rrender();qrev()};
window.invoiceRevRemove=id=>{S.rev.lines=S.rev.lines.filter(x=>x.id!==id);rrender();qrev()};
function qrev(){clearTimeout(S.rt);el('revStatus').textContent='Unsaved changes';S.rt=setTimeout(srev,700)}
async function srev(){if(!S.rev)return;el('revStatus').textContent='Saving…';const notes=el('revNotes').value,j=await api('invoice-save',{method:'POST',body:{invoice:{...S.rev,internal_notes:notes,internalNotes:notes,lines:S.rev.lines,payments:[]}}});S.rev=normalizeInvoice(j.invoice);el('revStatus').textContent='Saved';loadRev()}
window.invoiceCloseRevision=()=>{clearTimeout(S.rt);Promise.resolve(srev()).finally(()=>closeModal('revModal'))};
window.invoiceSendRevision=async()=>{if(!S.rev)return;clearTimeout(S.rt);await srev();invoice.lines=S.rev.lines.map(l=>({...l,id:uid()}));const n=el('revNotes').value.trim();if(n)invoice.internal_notes=[invoice.internal_notes,n].filter(Boolean).join('\n');await api('invoice',{method:'DELETE',params:{id:S.rev.id}});S.rev=null;closeModal('revModal');renderLines();queueSave();showTab('lines');loadRev()};
function revisions(){revModal();window.loadRevisions=loadRev;const old=window.showTab;window.showTab=n=>{const r=old(n);if(n==='revisions')loadRev();return r}}
function client(){let x=localStorage.getItem('shop_invoice_client_id');if(!x){x=crypto.randomUUID?crypto.randomUUID():'c'+Date.now();localStorage.setItem('shop_invoice_client_id',x)}return x}
async function lreq(method,b){const r=await fetch('/api/invoice-lock',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(b||{}),cache:'no-store'}),j=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,j}}
function banner(){if(el('lockBanner'))return;const b=document.createElement('div');b.id='lockBanner';b.className='lock-banner';document.querySelector('.docbar')?.before(b)}
function block(v,who){S.lock.blocked=v;const b=el('lockBanner');b.classList.toggle('show',v);b.innerHTML=v?'<strong>Read only:</strong> '+esc(who||'Another admin session')+' is editing this invoice.':'';editUI(v)}
function editUI(v){const q=['#tab-lines input','#tab-lines button','#tab-notes textarea','.main > aside:first-child input','.main > aside:first-child select','.main > aside:first-child button','.main > aside:last-child input','.main > aside:last-child select','.main > aside:last-child button','.workflow button','.top-actions button[onclick*="saveNow"]','.top-actions button[onclick*="closeCurrentInvoice"]'];document.querySelectorAll(q.join(',')).forEach(x=>{if(v){if(!x.disabled){x.dataset.locked='1';x.disabled=true}}else if(x.dataset.locked){x.disabled=false;delete x.dataset.locked}})}
async function acquire(id){if(!id||S.lock.busy)return !S.lock.blocked;S.lock.busy=true;S.lock.client=S.lock.client||client();S.lock.t=S.lock.t||((crypto.randomUUID&&crypto.randomUUID())||'t'+Date.now());const r=await lreq('POST',{action:'acquire',invoiceId:id,token:S.lock.t,clientId:S.lock.client,lockedBy:'Admin session '+S.lock.client.slice(-6)});S.lock.busy=false;if(r.j.locking===false){block(false);return true}if(r.status===409){S.lock.id=id;S.lock.owned=false;block(true,r.j.lockedBy);return false}if(!r.ok)return false;S.lock.id=id;S.lock.owned=true;block(false);clearInterval(S.lock.h);S.lock.h=setInterval(()=>lreq('POST',{action:'heartbeat',invoiceId:id,token:S.lock.t,clientId:S.lock.client}).then(x=>{if(x.status===409){S.lock.owned=false;block(true,x.j.lockedBy)}}),30000);return true}
async function release(){clearInterval(S.lock.h);if(S.lock.owned&&S.lock.id)try{await lreq('DELETE',{invoiceId:S.lock.id,token:S.lock.t})}catch(e){}S.lock.id=null;S.lock.owned=false;S.lock.blocked=false;S.lock.t='';block(false)}
function locks(){banner();S.lock.client=client();const os=window.saveNow;window.saveNow=async function(){if(S.lock.blocked){el('autosave').textContent='Read only · locked';return null}const r=await os.apply(this,arguments);if(invoice.id&&!S.lock.id)await acquire(invoice.id);return r};const oq=window.queueSave;window.queueSave=function(){if(S.lock.blocked){el('autosave').textContent='Read only · locked';return}return oq.apply(this,arguments)};const oo=window.openInvoice;window.openInvoice=async function(id){await release();const ok=await acquire(id),r=await oo.apply(this,arguments);if(!ok)block(true,'Another admin session');return r};const on=window.newDraft;window.newDraft=function(){release();return on.apply(this,arguments)};new MutationObserver(()=>{if(S.lock.blocked)editUI(true);else if(invoice.id&&!S.lock.id&&!S.lock.busy)acquire(invoice.id)}).observe(document.querySelector('.app'),{childList:true,subtree:true});window.addEventListener('beforeunload',()=>{if(S.lock.owned&&S.lock.id)fetch('/api/invoice-lock',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({invoiceId:S.lock.id,token:S.lock.t}),keepalive:true})});if(invoice.id)acquire(invoice.id)}
if(document.readyState==='complete')wait();else window.addEventListener('load',wait,{once:true});setTimeout(wait,100)
})();
