(function(){
  const path=String(location.pathname||'').replace(/\/+$/,'')||'/';
  if(!path.startsWith('/admin')||path.startsWith('/admin/invoice'))return;
  const cfg=window.SHOP_CONFIG||{};
  if(!document.querySelector('link[data-premium-admin]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/admin/premium-admin.css?v=5';l.setAttribute('data-premium-admin','true');document.head.appendChild(l)}
  const $=(s,r=document)=>r.querySelector(s);
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function titleFor(){if(path==='/admin')return['Command Center','Appointments, customer communication, and daily workflow'];if(path.includes('availability'))return['Shop Settings','Manage your business, technicians, and appointment availability'];if(path.includes('customers'))return['Customers','Customer profiles, vehicles, and service history'];if(path.includes('inspection-requests'))return['Inspections','Manage active requests and completed reports'];if(path.includes('inspection-history'))return['Inspections','Manage active requests and completed reports'];if(path.includes('inspection'))return['Create Inspection','Create and manage vehicle inspections'];return['Shop Admin','Manage your shop operations']}
  function active(href){if(href==='/admin'||href==='/admin/inspection')return path===href;return path.startsWith(href)}
  function goNew(){if(path==='/admin'&&typeof window.openCreateModal==='function')window.openCreateModal();else location.href='/admin?newAppointment=1'}
  function goMessages(){if(path==='/admin'){const b=$('#openTextPanelBtn');if(b)b.click();else location.href='/admin?messages=1'}else location.href='/admin?messages=1'}
  function logout(){fetch('/api/admin-logout',{method:'POST'}).catch(()=>{}).finally(()=>location.href='/admin')}
  function navItem(href,icon,label){return `<a href="${href}" class="${active(href)?'active':''}"><span class="pa-ico">${icon}</span><span>${label}</span></a>`}
  function installShell(){if($('#premiumAdminShell'))return;const t=titleFor();const shell=document.createElement('div');shell.id='premiumAdminShell';shell.innerHTML=`<div class="pa-menu-scrim"></div><aside class="pa-sidebar" id="paSidebar"><div class="pa-brand"><div class="pa-brand-mark"><div class="pa-logo">S</div><div><strong id="paShopName">${esc(cfg.name||'Auto Shop')}</strong><small>Shop Console</small></div></div></div><nav class="pa-nav"><div class="pa-nav-label">Workspace</div>${navItem('/admin','⌂','Overview')}<button id="paNew"><span class="pa-ico">＋</span><span>New Appointment</span></button>${navItem('/admin/customers','◉','Customers')}<button id="paMessages"><span class="pa-ico">✉</span><span>Messages</span></button><div class="pa-nav-label">Inspection Tools</div>${navItem('/admin/inspection-requests','▣','Inspections')}${navItem('/admin/inspection','✓','Create Inspection')}<div class="pa-nav-label">Shop</div>${navItem('/admin/availability','⚙','Settings')}<a href="/" target="_blank"><span class="pa-ico">↗</span><span>View Website</span></a><a href="/tech" target="_blank"><span class="pa-ico">↗</span><span>Technician Login</span></a></nav><div class="pa-side-foot"><button id="paLogout">Log out</button></div></aside><header class="pa-topbar"><div class="pa-topbar-left"><h1>${t[0]}</h1><p>${t[1]}</p></div><div class="pa-top-actions"><button class="pa-menu-btn secondary" id="paMenu" type="button" aria-label="Open navigation menu" aria-controls="paSidebar" aria-expanded="false"><span aria-hidden="true">☰</span><span>Menu</span></button></div></header>`;document.body.insertBefore(shell,document.body.firstChild);const closeMenu=()=>{document.body.classList.remove('pa-menu-open');$('#paMenu')?.setAttribute('aria-expanded','false')};const toggleMenu=()=>{const open=document.body.classList.toggle('pa-menu-open');$('#paMenu')?.setAttribute('aria-expanded',String(open))};$('#paNew').onclick=()=>{closeMenu();goNew()};$('#paMessages').onclick=()=>{closeMenu();goMessages()};$('#paLogout').onclick=logout;$('#paMenu').onclick=toggleMenu;$('.pa-menu-scrim').onclick=closeMenu;document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu()})}
  function applyShopIdentity(shop){if(!shop?.name)return;cfg.name=shop.name;const name=$('#paShopName');if(name)name.textContent=shop.name;document.querySelectorAll('.shopBrand').forEach(x=>x.textContent=shop.name)}
  async function refreshShopIdentity(){try{const r=await fetch('/api/admin-data?action=shop-settings',{cache:'no-store'});if(!r.ok)return;const j=await r.json();applyShopIdentity(j.shop)}catch(_){}}
  function showShell(){document.body.classList.add('pa-ready')}
  function enhanceDashboard(){if(path!=='/admin'||$('#paDashboardHead'))return;const dashboard=$('.dashboard');if(!dashboard)return;const head=document.createElement('section');head.id='paDashboardHead';head.className='pa-dashboard-head';const d=new Date();head.innerHTML=`<div class="pa-dashboard-head-inner"><div><h2>Good ${d.getHours()<12?'morning':d.getHours()<17?'afternoon':'evening'}.</h2><p>Here’s what’s happening with your shop today.</p></div><div class="pa-date-chip">${d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</div></div>`;dashboard.before(head)}
  function handleQuery(){if(path!=='/admin')return;const q=new URLSearchParams(location.search);if(q.get('newAppointment')==='1')setTimeout(()=>{if(typeof window.openCreateModal!=='function')return;window.openCreateModal();setTimeout(()=>{const values={cPhone:q.get('customerPhone'),cName:q.get('customerName'),cEmail:q.get('customerEmail')};Object.entries(values).forEach(([id,value])=>{const field=document.getElementById(id);if(field&&value){field.value=value;field.dispatchEvent(new Event('input',{bubbles:true}))}});const phone=document.getElementById('cPhone');if(phone&&values.cPhone)phone.dispatchEvent(new Event('blur',{bubbles:true}))},120)},450);if(q.get('messages')==='1')setTimeout(async()=>{if(typeof window.openTextPanel==='function')await window.openTextPanel();else $('#openTextPanelBtn')?.click();const name=$('#smsManualName'),phone=$('#smsManualPhone'),message=$('#smsMessage');if(name&&q.get('customerName'))name.value=q.get('customerName');if(phone&&q.get('customerPhone'))phone.value=q.get('customerPhone');if(message&&q.get('message')){message.value=q.get('message');message.dispatchEvent(new Event('input',{bubbles:true}));message.focus()}},500)}
  function hideInvoices(){document.querySelectorAll('a[href*="/admin/invoice"],button[data-invoice-link]').forEach(x=>x.remove())}
  function installMessageComposer(){const composer=$('#smsMessage');if(!composer||composer.dataset.autoGrow==='true')return;const resize=()=>{composer.style.height='auto';const height=Math.min(Math.max(composer.scrollHeight,44),innerWidth<=900?132:160);composer.style.height=height+'px';composer.style.overflowY=composer.scrollHeight>height?'auto':'hidden'};composer.dataset.autoGrow='true';composer.addEventListener('input',resize);window.resizeSmsComposer=resize;resize()}
  function boot(){installShell();enhanceDashboard();handleQuery();hideInvoices();installMessageComposer();refreshShopIdentity();window.addEventListener('shopidentitychange',e=>applyShopIdentity(e.detail));new MutationObserver(hideInvoices).observe(document.body,{childList:true,subtree:true});const login=$('#loginScreen'),admin=$('#adminDashboard');if(login&&admin){const sync=()=>{const visible=getComputedStyle(admin).display!=='none';document.body.classList.toggle('pa-ready',visible)};sync();new MutationObserver(sync).observe(admin,{attributes:true,attributeFilter:['style','class']});setInterval(sync,800)}else showShell()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
