(function(){
  const path=String(location.pathname||'').replace(/\/+$/,'')||'/';
  if(!path.startsWith('/admin')||path.startsWith('/admin/invoice'))return;
  const cfg=window.SHOP_CONFIG||{};
  if(!document.querySelector('link[data-premium-admin]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/admin/premium-admin.css?v=1';l.setAttribute('data-premium-admin','true');document.head.appendChild(l)}
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function titleFor(){if(path==='/admin')return['Command Center','Appointments, customer communication, and daily workflow'];if(path.includes('customers'))return['Customers','Customer profiles, vehicles, and service history'];if(path.includes('inspection-history'))return['Inspection History','Review completed digital inspections'];if(path.includes('inspection'))return['Digital Inspections','Create and manage vehicle inspections'];return['Shop Admin','Manage your shop operations']}
  function active(href){if(href==='/admin')return path==='/admin';return path.startsWith(href)}
  function goNew(){if(path==='/admin'&&typeof window.openCreateModal==='function')window.openCreateModal();else location.href='/admin?newAppointment=1'}
  function goMessages(){if(path==='/admin'){const b=$('#openTextPanelBtn');if(b)b.click();else location.href='/admin?messages=1'}else location.href='/admin?messages=1'}
  function logout(){fetch('/api/admin-logout',{method:'POST'}).catch(()=>{}).finally(()=>location.href='/admin')}
  function navItem(href,icon,label){return `<a href="${href}" class="${active(href)?'active':''}"><span class="pa-ico">${icon}</span><span>${label}</span></a>`}
  function installShell(){if($('#premiumAdminShell'))return;const t=titleFor();const shell=document.createElement('div');shell.id='premiumAdminShell';shell.innerHTML=`<div class="pa-menu-scrim"></div><aside class="pa-sidebar"><div class="pa-brand"><div class="pa-brand-mark"><div class="pa-logo">S</div><div><strong>${esc(cfg.name||'Auto Shop')}</strong><small>Shop Console</small></div></div></div><nav class="pa-nav"><div class="pa-nav-label">Workspace</div>${navItem('/admin','⌂','Overview')}<button id="paNew"><span class="pa-ico">＋</span><span>New Appointment</span></button><button id="paMessages"><span class="pa-ico">✉</span><span>Messages</span></button>${navItem('/admin/customers','◉','Customers')}<div class="pa-nav-label">Service Tools</div>${navItem('/admin/inspection','✓','Inspections')}${navItem('/admin/inspection-history','↺','Inspection History')}<div class="pa-nav-label">Website</div><a href="/" target="_blank"><span class="pa-ico">↗</span><span>View Website</span></a></nav><div class="pa-side-foot"><button id="paLogout">Log out</button></div></aside><header class="pa-topbar"><div class="pa-topbar-left"><h1>${t[0]}</h1><p>${t[1]}</p></div><div class="pa-top-actions"><button class="pa-menu-btn secondary" id="paMenu">☰</button><button class="secondary" id="paTopMessages">💬 Messages</button><button class="primary" id="paTopNew">＋ New Appointment</button></div></header>`;document.body.insertBefore(shell,document.body.firstChild);$('#paNew').onclick=goNew;$('#paTopNew').onclick=goNew;$('#paMessages').onclick=goMessages;$('#paTopMessages').onclick=goMessages;$('#paLogout').onclick=logout;$('#paMenu').onclick=()=>document.body.classList.toggle('pa-menu-open');$('.pa-menu-scrim').onclick=()=>document.body.classList.remove('pa-menu-open')}
  function showShell(){document.body.classList.add('pa-ready')}
  function stat(label,value,foot,icon){return `<div class="pa-stat"><div class="pa-stat-top"><span class="pa-stat-label">${label}</span><span class="pa-stat-icon">${icon}</span></div><div class="pa-stat-value">${value}</div><div class="pa-stat-foot">${foot}</div></div>`}
  function updateStats(){const box=$('#paStats');if(!box)return;const today=$$('.day.today .appointment-dot').length;const pendingTexts=new Set();$$('.status-pending,.status-new').forEach(x=>{const txt=(x.textContent||'').trim();if(txt)pendingTexts.add(txt)});const vals=$$('.pa-stat-value',box);if(vals[0])vals[0].textContent=String(today);if(vals[1])vals[1].textContent=String(pendingTexts.size)}
  function enhanceDashboard(){if(path!=='/admin'||$('#paDashboardHead'))return;const dashboard=$('.dashboard');if(!dashboard)return;const head=document.createElement('section');head.id='paDashboardHead';head.className='pa-dashboard-head';const d=new Date();head.innerHTML=`<div class="pa-dashboard-head-inner"><div><h2>Good ${d.getHours()<12?'morning':d.getHours()<17?'afternoon':'evening'}.</h2><p>Here’s what’s happening with your shop today.</p></div><div class="pa-date-chip">${d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</div></div>`;const stats=document.createElement('section');stats.id='paStats';stats.className='pa-stat-grid';stats.innerHTML=stat('Today','—','appointments','📅')+stat('Pending','—','awaiting confirmation','⏳')+stat('Messages','Open','customer inbox','💬')+stat('Customers','Profiles','customer database','👥');dashboard.before(head,stats);updateStats();new MutationObserver(updateStats).observe(dashboard,{subtree:true,childList:true,attributes:true})}
  function handleQuery(){if(path!=='/admin')return;const q=new URLSearchParams(location.search);if(q.get('newAppointment')==='1')setTimeout(()=>typeof window.openCreateModal==='function'&&window.openCreateModal(),450);if(q.get('messages')==='1')setTimeout(()=>$('#openTextPanelBtn')?.click(),500)}
  function hideInvoices(){document.querySelectorAll('a[href*="/admin/invoice"],button[data-invoice-link]').forEach(x=>x.remove())}
  function boot(){installShell();enhanceDashboard();handleQuery();hideInvoices();new MutationObserver(hideInvoices).observe(document.body,{childList:true,subtree:true});const login=$('#loginScreen'),admin=$('#adminDashboard');if(login&&admin){const sync=()=>{const visible=getComputedStyle(admin).display!=='none';document.body.classList.toggle('pa-ready',visible)};sync();new MutationObserver(sync).observe(admin,{attributes:true,attributeFilter:['style','class']});setInterval(sync,800)}else showShell()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
